import './index.html';
import './scss/app.scss';
import './i18n/en_GB.json';
import './fonts/kambi-icomoon.svg';
import './fonts/kambi-icomoon.eot';
import './fonts/kambi-icomoon.ttf';
import './fonts/kambi-icomoon.woff';
import './js/app.js';
import './mockSetupData.json';